"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Fragment } from "react";
import Sidebar from "@/app/sidebar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `Webel.ai`,
  description: `Generated by create next app`,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(`init root layout`);
  return (
    <html lang={`en`}>
      <>
        <Sidebar />
        <main className={`py-10 lg:pl-72`}>
          <div className={`px-4 sm:px-6 lg:px-8`}>{children}</div>
        </main>
      </>
    </html>
  );
}
